<Project Sdk="Microsoft.NET.Sdk">
  <ItemGroup>
    <ProjectReference Include="..\..\JeffDock.PluginContracts\JeffDock.PluginContracts.csproj" />
    <EmbeddedResource Include="Assets\icon.svg" LogicalName="JeffDock.Plugins.PiHole.icon.svg" />
  </ItemGroup>
  <PropertyGroup>
    <TargetFramework>net10.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWindowsForms>true</UseWindowsForms>
  </PropertyGroup>
</Project>
